In [6]:
# https://www.tensorflow.org/api_docs/python/tf/image/resize

import tensorflow as tf
import matplotlib.pyplot as plt

image = tf.constant([
 [1,0,0,0,0],
 [0,1,0,0,0],
 [0,0,1,0,0],
 [0,0,0,1,0],
 [0,0,0,0,1],
])
image

<tf.Tensor: shape=(5, 5), dtype=int32, numpy=
array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]], dtype=int32)>

In [7]:
def plot_one(image,label):
    plt.figure(figsize=(3, 3))
    plt.imshow(image)
    plt.title(int(label))
    plt.axis("off")

In [8]:
plot_one(image,4)

In [9]:
# Add "batch" and "channels" dimensions
image = image[tf.newaxis, ..., tf.newaxis]
image.shape.as_list()
tf.image.resize(image, [3,5])[0,...,0].numpy()
# image
# plot_one(image,4)

array([[0.6666667, 0.3333333, 0.       , 0.       , 0.       ],
       [0.       , 0.       , 1.       , 0.       , 0.       ],
       [0.       , 0.       , 0.       , 0.3333335, 0.6666665]],
      dtype=float32)