https://keras.io/guides/transfer_learning/#the-typical-transferlearning-workflow

Transfer learning & fine-tuning

In [23]:
import numpy as np
import tensorflow as tf
import keras
from keras import layers
import tensorflow_datasets as tfds
import matplotlib.pyplot as plt

In [31]:
layer = layers.Dense(1)
print("weights:", len(layer.weights))

layer.build((None, 3))  # Create the weights

print("weights:", len(layer.weights))
print("trainable_weights:", len(layer.trainable_weights))
print("non_trainable_weights:", len(layer.non_trainable_weights))
layer.weights

weights: 0
weights: 2
trainable_weights: 2
non_trainable_weights: 0


[<tf.Variable 'kernel:0' shape=(3, 1) dtype=float32, numpy=
 array([[ 0.6758677],
        [-1.0589191],
        [-1.0545548]], dtype=float32)>,
 <tf.Variable 'bias:0' shape=(1,) dtype=float32, numpy=array([0.], dtype=float32)>]

In [40]:
# https://keras.io/api/layers/

layer = layers.Dense(3, activation='relu')
print("weights:", len(layer.weights))
inputs = tf.random.uniform(shape=(2, 4))
print(inputs)
print("weights:", len(layer.weights))
outputs = layer(inputs)
print("weights:", len(layer.weights))

layer.weights

weights: 0
tf.Tensor(
[[0.83203757 0.39069557 0.59502244 0.16532624]
 [0.6601567  0.63252306 0.6119627  0.24258316]], shape=(2, 4), dtype=float32)
weights: 0
weights: 2


[<tf.Variable 'dense_30/kernel:0' shape=(4, 3) dtype=float32, numpy=
 array([[-0.12179631,  0.70508564,  0.42845058],
        [ 0.38877916, -0.63593096,  0.71680593],
        [ 0.81378055,  0.1370902 , -0.886665  ],
        [ 0.2338264 ,  0.7273531 , -0.67388684]], dtype=float32)>,
 <tf.Variable 'dense_30/bias:0' shape=(3,) dtype=float32, numpy=array([0., 0., 0.], dtype=float32)>]

In [26]:
layer = keras.layers.BatchNormalization()
layer.build((None, 4))  # Create the weights

print("weights:", len(layer.weights))
print("trainable_weights:", len(layer.trainable_weights))
print("non_trainable_weights:", len(layer.non_trainable_weights))

weights: 4
trainable_weights: 2
non_trainable_weights: 2


In [ ]:
layer = keras.layers.Dense(3)
layer.build((None, 4))  # Create the weights
layer.trainable = False  # Freeze the layer

print("len weights:", len(layer.weights))
print("weights:", layer.weights)
# print("weights:", layer.weights['numpy'])
# print("weights shape:", layer.weights.shape)
print("trainable_weights:", len(layer.trainable_weights))
print("non_trainable_weights:", len(layer.non_trainable_weights))

len weights: 2
weights: [<tf.Variable 'kernel:0' shape=(4, 3) dtype=float32, numpy=
array([[ 0.84600973,  0.58557653, -0.25327557],
       [-0.78375363,  0.89454293,  0.7059549 ],
       [ 0.7317718 ,  0.43506908, -0.2673062 ],
       [ 0.51457655,  0.70768857, -0.7440595 ]], dtype=float32)>, <tf.Variable 'bias:0' shape=(3,) dtype=float32, numpy=array([0., 0., 0.], dtype=float32)>]


TypeError: list indices must be integers or slices, not str

In [43]:
# Make a model with 2 layers
layer1 = keras.layers.Dense(3, activation="relu")
layer2 = keras.layers.Dense(3, activation="sigmoid")
model = keras.Sequential([keras.Input(shape=(3,)), layer1, layer2])

# Freeze the first layer
layer1.trainable = False

# Keep a copy of the weights of layer1 for later reference
initial_layer1_weights_values = layer1.get_weights()
print(initial_layer1_weights_values)


# Train the model
model.compile(optimizer="adam", loss="mse")
model.fit(np.random.random((2, 3)), np.random.random((2, 3)))

# Check that the weights of layer1 have not changed during training
final_layer1_weights_values = layer1.get_weights()
np.testing.assert_allclose(
    initial_layer1_weights_values[0], final_layer1_weights_values[0]
)
np.testing.assert_allclose(
    initial_layer1_weights_values[1], final_layer1_weights_values[1]
)

[array([[ 0.81651115, -0.14896321,  0.41293025],
       [-0.48288417, -0.6943476 ,  0.613925  ],
       [ 0.8249855 ,  0.8214996 ,  0.23485398]], dtype=float32), array([0., 0., 0.], dtype=float32)]
1/1 [==============================] - 0s 184ms/step - loss: 0.0724
