###  MicroGrad demo

In [1]:
import random
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
from mycrograd_debug.engine_debug import Value
from mycrograd_debug.nn_debug import Neuron, Layer, MLP
from mycrograd_debug.drawviz_debug import draw_dot,draw_nn,print_all_values
import pprint
np.random.seed(1337)
random.seed(1337)
number_of_samples=2
number_of_iterations=2
pp = pprint.PrettyPrinter(indent=4)

In [2]:
# make up a dataset

from sklearn.datasets import make_moons, make_blobs
X, y = make_moons(n_samples=number_of_samples, noise=0.1)
pp.pprint(X)
pp.pprint(y)
y = y*2 - 1 # make y be -1 or 1
pp.pprint(y)

array([[ 0.8572558 ,  0.03006228],
       [-0.05120403,  0.50473341]])
array([0, 1])
array([-1,  1])


In [3]:
# initialize a model 
# model = MLP(2, [16, 16, 1]) # 2-layer neural network
model = MLP(2, [2, 1], debug_bw=False) # 2-layer neural network
# print(model)
# pp.pprint(model.parameters())
Xb, yb = X, y
inputs = [list(map(Value, xrow)) for xrow in Xb]
pp.pprint(inputs)
for i in range(len(inputs)):
    for j in range(len(inputs[i])):
        inputs[i][j].type = "i"
pp.pprint(inputs)

Module nn MLP: structure [2, 2, 1]
[   [   Value(name=v010,layernumber=,neuronnumber=,weightnumber=,type=,data=0.8572557995669348, grad=0),
        Value(name=v011,layernumber=,neuronnumber=,weightnumber=,type=,data=0.03006227935826109, grad=0)],
    [   Value(name=v012,layernumber=,neuronnumber=,weightnumber=,type=,data=-0.051204029028939925, grad=0),
        Value(name=v013,layernumber=,neuronnumber=,weightnumber=,type=,data=0.5047334093296381, grad=0)]]
[   [   Value(name=v010,layernumber=,neuronnumber=,weightnumber=,type=i,data=0.8572557995669348, grad=0),
        Value(name=v011,layernumber=,neuronnumber=,weightnumber=,type=i,data=0.03006227935826109, grad=0)],
    [   Value(name=v012,layernumber=,neuronnumber=,weightnumber=,type=i,data=-0.051204029028939925, grad=0),
        Value(name=v013,layernumber=,neuronnumber=,weightnumber=,type=i,data=0.5047334093296381, grad=0)]]


In [4]:
# loss function
def loss():
    
    # forward the model to get scores
    scores = list(map(model, inputs))
    
    # svm "max-margin" loss
    losses = [(1 + -yi*scorei).relu() for yi, scorei in zip(yb, scores)]
    data_loss = sum(losses) * (1.0 / len(losses))
    # L2 regularization
    alpha = 1e-4
    reg_loss = alpha * sum((p*p for p in model.parameters()))
    total_loss = data_loss + reg_loss
    
    # also get accuracy
    accuracy = [(yi > 0) == (scorei.data > 0) for yi, scorei in zip(yb, scores)]
    return total_loss, sum(accuracy) / len(accuracy)

total_loss, acc = loss()
print(total_loss, acc)

Value(name=v078,layernumber=,neuronnumber=,weightnumber=,type=,data=0.9065883811424296, grad=0) 1.0


In [5]:


# optimization
for k in range(number_of_iterations):
    print("start")
    # pp.pprint(model.parameters())

    # forward
    total_loss, acc = loss()
    print_all_values(total_loss)
    dot=draw_dot(total_loss)
    dot.render("images/opt_01_step%d_1loss" % k , format="svg", view=True)

    # backward
    model.zero_grad()
    dot=draw_dot(total_loss)
    dot.render("images/opt_01_step%d_2zero" % k , format="svg", view=True)

    total_loss.backward()
    dot=draw_dot(total_loss)
    dot.render("images/opt_01_step%d_3back" % k , format="svg", view=True)
    
    # update (sgd)
    learning_rate = 1.0 - 0.9*k/100
    for p in model.parameters():
        p.data -= learning_rate * p.grad
    
    if k % 1 == 0:
        print(f"step {k} loss {total_loss.data}, accuracy {acc*100}%")


start
[   {'data': 0.23550571390294128, 'grad': 0, 'name': 'v001', 'type': 'w1'},
    {'data': 0.06653114721000164, 'grad': 0, 'name': 'v002', 'type': 'w2'},
    {'data': 0, 'grad': 0, 'name': 'v003', 'type': 'b'},
    {'data': -0.26830328150124894, 'grad': 0, 'name': 'v004', 'type': 'w1'},
    {'data': 0.1715747078045431, 'grad': 0, 'name': 'v005', 'type': 'w2'},
    {'data': 0, 'grad': 0, 'name': 'v006', 'type': 'b'},
    {'data': -0.6686254326224383, 'grad': 0, 'name': 'v007', 'type': 'w1'},
    {'data': 0.6487474938152629, 'grad': 0, 'name': 'v008', 'type': 'w2'},
    {'data': 0, 'grad': 0, 'name': 'v009', 'type': 'b'},
    {'data': 0.8572557995669348, 'grad': 0, 'name': 'v010', 'type': 'i'},
    {'data': 0.03006227935826109, 'grad': 0, 'name': 'v011', 'type': 'i'},
    {'data': -0.051204029028939925, 'grad': 0, 'name': 'v012', 'type': 'i'},
    {'data': 0.5047334093296381, 'grad': 0, 'name': 'v013', 'type': 'i'},
    {'data': 0.2018886390744477, 'grad': 0, 'name': 'v079', 'type': 

/snap/core20/current/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /lib/x86_64-linux-gnu/libproxy.so.1)
Failed to load module: /home/tmeng12/snap/code/common/.cache/gio-modules/libgiolibproxy.so
/snap/core20/current/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /lib/x86_64-linux-gnu/libproxy.so.1)
Failed to load module: /home/tmeng12/snap/code/common/.cache/gio-modules/libgiolibproxy.so
eog: symbol lookup error: /snap/core20/current/lib/x86_64-linux-gnu/libpthread.so.0: undefined symbol: __libc_pthread_init, version GLIBC_PRIVATE
Failed to register: GDBus.Error:org.freedesktop.DBus.Error.NoReply: Message recipient disconnected from message bus without replying
/snap/core20/current/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /lib/x86_64-linux-gnu/libproxy.so.1)
Failed to load module: /home/tmeng12/snap/code/common/.cache/gio-modules/libgiolibproxy.so
/snap/core20/curren

step 1 loss 0.6796366507619458, accuracy 100.0%


eog: symbol lookup error: /snap/core20/current/lib/x86_64-linux-gnu/libpthread.so.0: undefined symbol: __libc_pthread_init, version GLIBC_PRIVATE
/snap/core20/current/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /lib/x86_64-linux-gnu/libproxy.so.1)
Failed to load module: /home/tmeng12/snap/code/common/.cache/gio-modules/libgiolibproxy.so
eog: symbol lookup error: /snap/core20/current/lib/x86_64-linux-gnu/libpthread.so.0: undefined symbol: __libc_pthread_init, version GLIBC_PRIVATE
Failed to register: GDBus.Error:org.freedesktop.DBus.Error.NoReply: Message recipient disconnected from message bus without replying


/snap/core20/current/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /lib/x86_64-linux-gnu/libproxy.so.1)
Failed to load module: /home/tmeng12/snap/code/common/.cache/gio-modules/libgiolibproxy.so
eog: symbol lookup error: /snap/core20/current/lib/x86_64-linux-gnu/libpthread.so.0: undefined symbol: __libc_pthread_init, version GLIBC_PRIVATE
