###  print out structures

In [1]:
import random
import numpy as np
from mycrograd_debug.engine_debug import Value
from mycrograd_debug.nn_debug import Neuron, Layer, MLP, MLP_linear
from mycrograd_debug.drawviz_debug import draw_dot

np.random.seed(1337)
random.seed(1337)

#### Multi Layer Perceptron

In [2]:
# loss function single MLP
def loss_single(target,output):
    total_loss = (output - target)
    return total_loss

In [3]:
# initialize a model 
nin=3  #number of inputs
Value.value_counter=0

model = MLP_linear(nin, [4, 4, 1]) # 2-layer neural network
xinumbers= np.random.randint(1,10, size=(nin))   # inputs
xi = [Value(x,type='i') for x in xinumbers]
print("inputs ", xi)


#ys = [[1.0]]  
ys=Value(1.2) # desired targets

ypred = model(xi)

loss=loss_single(ypred,ys)

#loss=ypred
print("loss= ",loss)
print("number of Value objects created = ",Value.value_counter)

draw_dot(loss, debug_print_01=False)

neuron nonlin is  False
neuron nonlin is  False
neuron nonlin is  False
neuron nonlin is  False
neuron nonlin is  False
neuron nonlin is  False
neuron nonlin is  False
neuron nonlin is  False
neuron nonlin is  False
inputs  [Value(name=val42,type=i,data=8, grad=0), Value(name=val43,type=i,data=9, grad=0), Value(name=val44,type=i,data=8, grad=0)]
loss=  Value(name=val112,type=,data=3.348938966870495, grad=0)
number of Value objects created =  112


#### Multiple Multi Layer Perceptrons

In [4]:
# loss function multiple MLP's
def loss_mult(targets,outputs):
    total_loss = sum((yout - ygt) ** 2 for ygt, yout in zip(outputs, targets))
    return total_loss


In [5]:
# initialize a model 
nin=3  #number of inputs
Value.value_counter=0

xs2=np.random.randint(1,10, size=(4,nin))   # inputs
print(xs2)

model = MLP(nin, [4, 4, 1]) # 2-layer neural network
xs2=np.random.randint(1,10, size=(3,4))   # inputs
ys = [1.0, -1.0, -1.0, 1.0]  # desired targets
ypred = [model(x) for x in xs2]

loss=loss_mult(ypred,ys)
print(loss)
print("number of Value objects created = ",Value.value_counter)
loss.backward()

draw_dot(loss)



[[8 3 3]
 [5 9 7]
 [7 8 9]
 [2 7 7]]
neuron nonlin is  True
neuron nonlin is  True
neuron nonlin is  True
neuron nonlin is  True
neuron nonlin is  True
neuron nonlin is  True
neuron nonlin is  True
neuron nonlin is  True
neuron nonlin is  False
Value(name=val306,type=,data=35.01992464544722, grad=0)
number of Value objects created =  306
